In [2]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Hp\Downloads\NayShin_Code\QVI_purchase_behaviour.csv')
df2 = pd.read_csv(r'C:\Users\Hp\Downloads\NayShin_Code\QVI_transaction_data.csv')

In [3]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATE            264836 non-null  int64
 1   STORE_NBR       264836 non-null  int64
 2   LYLTY_CARD_NBR  264836 non-null  int64
 3   TXN_ID          264836 non-null  int64
 4   PROD_NBR        264836 non-null  int64
 5   PROD_NAME       264836 non-null  object
 6   PROD_QTY        264836 non-null  int64
 7   TOT_SALES       264836 non-null  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 16.2+ MB

In [4]:
df2.describe()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_QTY,TOT_SALES
count,264836.000000,264836.00000,2.648360e+05,2.648360e+05,264836.000000,264836.000000,264836.000000
mean,43464.036260,135.08011,1.355495e+05,1.351583e+05,56.583157,1.907309,7.304200
std,105.389282,76.78418,8.057998e+04,7.813303e+04,32.826638,0.643654,3.083226
min,43282.000000,1.00000,1.000000e+03,1.000000e+00,1.000000,1.000000,1.500000
25%,43373.000000,70.00000,7.002100e+04,6.760150e+04,28.000000,2.000000,5.400000
50%,43464.000000,130.00000,1.303575e+05,1.351375e+05,56.000000,2.000000,7.400000
75%,43555.000000,203.00000,2.030942e+05,2.027012e+05,85.000000,2.000000,9.200000
max,43646.000000,272.00000,2.373711e+06,2.415841e+06,114.000000,200.000000,650.000000

In [5]:
df2['PROD_NAME'].value_counts()

PROD_NAME
Kettle Mozzarella   Basil & Pesto 175g      3304
Kettle Tortilla ChpsHny&Jlpno Chili 150g    3296
Cobs Popd Swt/Chlli &Sr/Cream Chips 110g    3269
Tyrrells Crisps     Ched & Chives 165g      3268
Cobs Popd Sea Salt  Chips 110g              3265
                                            ...
RRD Pc Sea Salt     165g                    1431
Woolworths Medium   Salsa 300g              1430
NCC Sour Cream &    Garden Chives 175g      1419
French Fries Potato Chips 175g              1418
WW Crinkle Cut      Original 175g           1410
Name: count, Length: 114, dtype: int64

In [6]:
df2['PROD_QTY'].value_counts()

PROD_QTY
2      236039
1       27518
5         450
3         430
4         397
200         2
Name: count, dtype: int64

In [7]:
df2['TOT_SALES'].value_counts()

TOT_SALES
9.2      22821
7.4      22513
6.0      20798
7.6      20212
8.8      19900
         ...
9.3          3
6.9          3
12.4         2
650.0        2
11.2         2
Name: count, Length: 112, dtype: int64

In [12]:
df2['DATE']=pd.to_datetime(df2['DATE'],unit='D',origin='1900-01-01')

In [14]:
df2.describe()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_QTY,TOT_SALES,Date
count,264836,264836.00000,2.648360e+05,2.648360e+05,264836.000000,264836.000000,264836.000000,264836
mean,2019-01-01 00:52:12.879215616,135.08011,1.355495e+05,1.351583e+05,56.583157,1.907309,7.304200,2019-01-01 00:52:12.879215616
min,2018-07-03 00:00:00,1.00000,1.000000e+03,1.000000e+00,1.000000,1.000000,1.500000,2018-07-03 00:00:00
25%,2018-10-02 00:00:00,70.00000,7.002100e+04,6.760150e+04,28.000000,2.000000,5.400000,2018-10-02 00:00:00
50%,2019-01-01 00:00:00,130.00000,1.303575e+05,1.351375e+05,56.000000,2.000000,7.400000,2019-01-01 00:00:00
75%,2019-04-02 00:00:00,203.00000,2.030942e+05,2.027012e+05,85.000000,2.000000,9.200000,2019-04-02 00:00:00
max,2019-07-02 00:00:00,272.00000,2.373711e+06,2.415841e+06,114.000000,200.000000,650.000000,2019-07-02 00:00:00
std,NaN,76.78418,8.057998e+04,7.813303e+04,32.826638,0.643654,3.083226,NaN

In [18]:
df2.dropna(subset=['TXN_ID','TOT_SALES'],inplace=True)
print(len(df2))

264836